name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nikitamadule/task:latest
    - name: Push the Docker image
      run: docker login -u nikitamadule -p ${{ secrets.DOCKER_TASK }} && docker push nikitamadule/task:latest


